[package]
name = "macro-egs"
version = "0.1.0"
authors = ["Chen Weiguang <chen.weiguang@gmail.com>"]
edition = "2018"

[workspace]
members = [
    "decorator",
]

[[example]]
name = "decorator-eg"

[dependencies]
decorator = { path = "decorator" }
